### ISSUE TITLE
Client dies when Server never sends the desktop-name in the rfb server framebuffer params

### ISSUE THREAD

**Issue by Endunry** [zocker-160/pyQVNCWidget#10]
I use this for a internal tool and was testing with a simple vnc server that is actually using rfb 3.3 and now i wanted to use it on an actual "prod"-enviroment. Which uses rfb 3.8. When testing it, i faced a black screen without any error messages in the console appearing. First i thought this was an issue with rfb 3.8 but it seems that the version negotiation worked and the server is using 3.3 (Checked with wireshark).

When debugging i saw that the Client died in the `RFBClient._handleServerInit`-Function because the server i am using rn is not sending information about the desktop name, in the packet there is only the padding and nothing more. So i just deleted the receive call for the desktop namelen and it worked.

I would just create a pull request, however im really not that deep into the libraries used and such so i thought maintainers could do this much more quickly. Maybe in the next days i will read more into it and maybe add a "Exception handling" (I guess the way the server does it may not be rfb specification but this seems like an easy fix to "support" it)

RFB Server framebuffer parameter Payload on ok server:
0000   05 56 03 00 20 20 00 01 00 ff 00 ff 00 ff 10 08   .V..  ..........
0010   00 00 00 00 00 00 00 03 48 4d 49                       ........HMI

RFB Server framebuffer parameter Payload on wrong server:
0000   03 20 01 e0 20 20 00 01 00 ff 00 ff 00 ff 10 08   . ..  ..........
0010   00 00 00 00 00 00 00 00                                      ........

As i said i know this is probably not specification and the library is not at fault and even if its specification its a wrong rfb version, just thought i might add this here. And maybe fix it myself in the future

**Comment by zocker-160** [comment]
First thank you for this report.

Something does not add up here though, the payload of the "ok server" is missing 2 bytes, I suspect a copy paste error?

When enabling the debug log, do you get the message `Connecting to`?

The payload of the "wrong server" is actually correct and I think I found the problem, will push a fix in a few minutes.

**Comment by zocker-160** [comment]
I pushed a new version to PyPi, please let me know if that works for you.

**Comment by Endunry** [comment]
Works perfectly, thanks!
