### ISSUE TITLE
Problems running with TigerVNC

### ISSUE THREAD

**Issue by fraviofii** [zocker-160/pyQVNCWidget#6]
I'm trying to execute the widget with TigerVNC and it is not working.

I set my vncserver with the following command:

```
vncserver -depth 24 :1
```

Then I launch the `example1.py` and I get the following screen:

![image](https://github.com/zocker-160/pyQVNCWidget/assets/2706129/71091712-ace3-461f-8412-61ad39dae560)

The connection is established and the VNC screen is showing on the screen. But only on the white line of the dialog.

Can you advise me on how to have this working?

**Comment by zocker-160** [comment]
Thank you for reporting, I think this might be a very similar issue to the RealVNC one.

Sadly I am currently short on time, but I will take a look, it is very likely a bug in the input buffer code rendering the first incoming image.

**Comment by zocker-160** [comment]
should be fixed with v0.3.x
